; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29337.0 

;q include listing.inc

;q INCLUDELIB LIBCMT
;q INCLUDELIB OLDNAMES

PUBLIC	message_text
PUBLIC	message_title
PUBLIC	buttons

_DATA	SEGMENT

message_text DQ	$SG6066

$SG6066	DB	'Is it 42?', 00H

	ORG $+6

message_title DQ $SG6068

$SG6068	DB	'Hello World.', 00H

	ORG $+3

buttons	DD	04H

_DATA	ENDS
END
