; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29337.0 

; include listing.inc
; 
; INCLUDELIB LIBCMT
; INCLUDELIB OLDNAMES

PUBLIC	func

EXTRN	MessageBoxA:PROC
EXTRN	message_text:QWORD
EXTRN	message_title:QWORD
EXTRN	buttons:DWORD

; q pdata	SEGMENT
; q $pdata$func DD	imagerel $LN3
; q 	DD	imagerel $LN3+45
; q 	DD	imagerel $unwind$func
; q pdata	ENDS
; q 
; q xdata	SEGMENT
; q $unwind$func DD	010401H
; q 	DD	06204H
; q xdata	ENDS

; Function compile flags: /Odtp
_TEXT	SEGMENT

ret$ = 32

func	PROC
; File C:\Users\Rene\github\temp\hacking-reverse-engineering-deubgging-assembler\windows\PE-COFF-Format\first\func.c
; Line 12
;q $LN3:
	sub	rsp, 56					; 00000038H
; Line 14
	mov	r9d, DWORD PTR buttons
	mov	r8 , QWORD PTR message_title
	mov	rdx, QWORD PTR message_text
	xor	ecx, ecx
	call	MessageBoxA
	mov	DWORD PTR ret$[rsp], eax

	mov	ecx, DWORD PTR ret$[rsp]
	call	twice

	add	rsp, 56					; 00000038H
	ret	0
func	ENDP

;q _TEXT	ENDS
;q ; Function compile flags: /Odtp
;q 
;q _TEXT	SEGMENT

x$ = 8

twice	PROC
  ;
  ;   Function that returns its only int-argument doubled.
  ;
  ;   Note: unike func, twice is not declared 'PUBLIC'
  ;


; File C:\Users\Rene\github\temp\hacking-reverse-engineering-deubgging-assembler\windows\PE-COFF-Format\first\func.c
; Line 12
; mov	DWORD PTR [rsp+8], ecx
; Line 13
	mov	eax, DWORD PTR x$[rsp]
	shl	eax, 1
; Line 14
	ret	0
twice	ENDP

_TEXT	ENDS
END
