set width 0
set height 0
set verbose off

b _start

run

set $argc   =  * (int*   ) ( $rsp +  0 )

set $argv_0 =  * (char** ) ( $rsp +  8 )
set $argv_1 =  * (char** ) ( $rsp + 16 )
set $argv_2 =  * (char** ) ( $rsp + 24 )
set $argv_3 =  * (char** ) ( $rsp + 32 )
                                          # NULL
set $envp_0 =  * (char***) ( $rsp + 48 )
set $envp_1 =  * (char***) ( $rsp + 56 )
set $envp_2 =  * (char***) ( $rsp + 64 )

p $argc
p $argv_0
p $argv_1
p $argv_2
p $argv_3



printf "argc    = %d\n",  $argc

printf "argv[0] = %s\n",  $argv_0
printf "argv[1] = %s\n",  $argv_1
printf "argv[2] = %s\n",  $argv_2
printf "argv[3] = %s\n",  $argv_3

printf "envp[0] = %s\n",   $envp_0
printf "envp[1] = %s\n",   $envp_1
printf "envp[2] = %s\n",   $envp_2

continue

